/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author Kevin
 */
public class LoadingPage extends javax.swing.JFrame {
    private float alpha;
    private Image before;
    private Timer timer=new Timer(15,new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent ae) {
            alpha += 0.01f;
            if (alpha >= 1f) {
                alpha = 1f; 
                timer.stop();
            }
            lblBack.repaint();
        }
    });
    private Timer timer1=new Timer(15,new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent ae) {
            alpha += -0.01f;
            if (alpha <= 0.25f) {
                alpha = 0.25f; 
                timer1.stop();
            }
            lblBack.repaint();
        }
    });
    

    /**
     * Creates new form LoadingPage
     */
    public LoadingPage() {
        initComponents();
        setFrameToTransparent();
        setlblOnlyImage();
        setFrameIcon();
        setTextAreaTransparent();
        new Thread(){
            @Override
            public void run(){
                int count=0;
                try{
                    while(true){
                        count++;
                        if(count!=1){
                            Thread.sleep(1350);
                        }
                        alpha=0.25f;
                        timer.start();
                        Thread.sleep(1350);
                        alpha=1f;
                        timer1.start();
                    }
                }catch(Exception e){}
                
            }
        }.start();
        setVisible(true);
    }
    
    private void setFrameToTransparent(){
        setLocationRelativeTo(null);
    }
    
    private void setlblOnlyImage(){
            Image img=new ImageIcon(getClass().getResource("/Resources/lolo0073.png")).getImage();
            Image scaled=img.getScaledInstance(lblOnly.getWidth(),lblOnly.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon resized=new ImageIcon(scaled);
            lblOnly.setIcon(resized);
            Image img1=new ImageIcon(getClass().getResource("/Resources/images/1575904.jpg")).getImage();
            before=img1.getScaledInstance(lblBack.getWidth(),lblBack.getHeight(), Image.SCALE_SMOOTH);
    }
    
    private void setFrameIcon(){
            setIconImage(new ImageIcon(getClass().getResource("/Resources/lolo0073.png")).getImage());  
    }
    
    private void setTextAreaTransparent(){
        scrlOnly.setOpaque(false);
        scrlOnly.getViewport().setOpaque(false);
        scrlOnly.setBorder(null);
        scrlOnly.setViewportBorder(null);
        txtOnly.setBorder(null);
        txtOnly.setBackground(new Color(0,0,0,64));
        progressOnly.setBorder(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                lblOnly = new javax.swing.JLabel();
                progressOnly = new javax.swing.JProgressBar();
                scrlOnly = new javax.swing.JScrollPane();
                txtOnly = new javax.swing.JTextArea();
                lblBack = lblBack=new JLabel(){
                        public void paintComponent(Graphics g){
                                try{
                                        ImageIcon temp=new ImageIcon(before);
                                        Image form=temp.getImage();
                                        Graphics2D g2d=(Graphics2D) g;
                                        g2d.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER,alpha));
                                        g2d.drawImage(form,0,0, null);
                                }catch(NullPointerException npe){}
                        }
                };

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setUndecorated(true);
                setPreferredSize(new java.awt.Dimension(396, 287));
                setResizable(false);
                setSize(new java.awt.Dimension(396, 287));
                getContentPane().setLayout(null);
                getContentPane().add(lblOnly);
                lblOnly.setBounds(148, 12, 100, 100);

                progressOnly.setBackground(new java.awt.Color(0, 204, 0));
                progressOnly.setForeground(new java.awt.Color(0, 0, 0));
                progressOnly.setOpaque(false);
                progressOnly.setStringPainted(true);
                getContentPane().add(progressOnly);
                progressOnly.setBounds(12, 124, 372, 32);

                txtOnly.setEditable(false);
                txtOnly.setColumns(20);
                txtOnly.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
                txtOnly.setForeground(new java.awt.Color(255, 255, 255));
                txtOnly.setRows(5);
                scrlOnly.setViewportView(txtOnly);

                getContentPane().add(scrlOnly);
                scrlOnly.setBounds(12, 162, 372, 113);
                getContentPane().add(lblBack);
                lblBack.setBounds(0, 0, 400, 300);

                pack();
        }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        new LoadingPage();
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel lblBack;
        private javax.swing.JLabel lblOnly;
        public javax.swing.JProgressBar progressOnly;
        private javax.swing.JScrollPane scrlOnly;
        public javax.swing.JTextArea txtOnly;
        // End of variables declaration//GEN-END:variables
}
